---
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH <info@univention.de>

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.20.0"
    file:
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/package-and-publish-helm-charts-souvap.yaml"


variables:
  # Used by pre-commit/gitlab-ci-linter
  GITLAB_PRIVATE_TOKEN: "${GITLAB_TOKEN}"
  GITLAB_PROJECT_ID: "${CI_PROJECT_ID}"
  GITLAB_SERVER: "https://git.knut.univention.de"

lint-pre-commit:
  before_script:
    - helm repo add bitnami "https://charts.bitnami.com/bitnami"

...
