---
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH <info@univention.de>

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.36.1"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"


variables:
  # Used by pre-commit/gitlab-ci-linter
  GITLAB_PRIVATE_TOKEN: "${GITLAB_TOKEN}"
  GITLAB_PROJECT_ID: "${CI_PROJECT_ID}"
  GITLAB_SERVER: "https://git.knut.univention.de"
  SKIP_UPDATE_HELM_VALUES: "1"

lint-pre-commit:
  before_script:
    - helm repo add bitnami "https://charts.bitnami.com/bitnami"

test-chart-unit:
  stage: test
  image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/common-helm/testrunner:0.6.1"
  script:
    - helm dep build helm/nats
    - pytest

...
