{{/*
SPDX-FileCopyrightText: 2024 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- if not (.Values.config.createUsers.adminUser.auth.existingSecret).name }}
{{- $name := include "nubus-common.secrets.name" (dict "defaultNameSuffix" "admin" "context" .) | quote -}}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ $name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- if (.Values.global.secrets).keep }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- if .Values.additionalAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  password: {{ coalesce
    (.Values.config.createUsers.adminUser.auth).password
    (printf "nbs_%s" (print (derivePassword 1 "long" .Values.global.secrets.masterPassword "nubus" "provisioning-nats") | sha1sum)
  ) | quote }}
{{- end }}
