# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

global:
  secrets:
    masterPassword: "nubus"
  kubeVersion: "1.2.4"


resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "64Mi"

nats:
  extraEnvVars:
    - name: "EXAMPLE"
      value: "example"
